version: '3.8'
services:
 dev-words-database: 
  image: postgres:15.0
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: words
  networks:
   - networks-nestjs 
networks:
  networks-nestjs: